config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :suggestions
  get 'home/index'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :suggestion, foreign_key: :suggestion_id
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord

  has_many :comments, foreign_key: :suggestion_id

  validates :title, presence: true
  validates :suggestion, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:suggestion_id, :comment, :active_status, :del_status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: [:show, :edit, :update, :destroy]

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = Suggestion.all.order('id desc')
    @suggestion = Suggestion.new
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
  end

  # GET /suggestions/new
  def new
    @suggestion = Suggestion.new
  end

  # GET /suggestions/1/edit
  def edit
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(suggestion_params)

    respond_to do |format|
      if @suggestion.save
        # format.html { redirect_to @suggestion, notice: 'Suggestion was successfully created.' }
        format.js {redirect_to suggestions_url, notice: "Thank you for your suggestion!"}
        format.json { render :show, status: :created, location: @suggestion }
      else
        format.js { render :new }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggestions/1
  # PATCH/PUT /suggestions/1.json
  def update
    respond_to do |format|
      if @suggestion.update(suggestion_params)
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.html { render :edit }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    @suggestion.destroy
    respond_to do |format|
      format.html { redirect_to suggestions_url, notice: 'Suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_suggestion
    @suggestion = Suggestion.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def suggestion_params
    params.require(:suggestion).permit(:title, :suggestion, :active_status, :del_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :suggestion_id %>
    <%= f.input :comment %>
    <%= f.input :active_status %>
    <%= f.input :del_status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Suggestion</th>
      <th>Comment</th>
      <th>Active status</th>
      <th>Del status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.suggestion_id %></td>
        <td><%= comment.comment %></td>
        <td><%= comment.active_status %></td>
        <td><%= comment.del_status %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Suggestion:</strong>
  <%= @comment.suggestion_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @comment.active_status %>
</p>

<p>
  <strong>Del status:</strong>
  <%= @comment.del_status %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<div class="valign-wrapper ">
  <div class="row">
    <h3 class="center">Welcome to SCA Groceries</h3>
    <p class="right-align ">Remember your feedback and Suggestions are of essence to us</p>
    <div class="center-align">
      <%= link_to suggestions_url, class: "btn white-text btn-large blue" do %>
        <span>Suggestions <i class="material-icons right">navigate_next</i></span>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ScaGrocery</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
<main role="main" class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</main>
</body>
</html>

app/views/suggestions/_form.html.erb
<%= simple_form_for @suggestion, remote: true do |f| %>
  <div class="container">
    <div class="row">
      <div class="input-field col s12">
        <%= f.input :title, label: false, placeholder: "Title" %>
        <%#= f.label :title, "Title" %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :suggestion,
                        class: "materialize-textarea",
                        id: "suggestion",
                        placeholder: "Type your suggestion here",
                        rows: '5'
        %>
        <%#= f.label :suggestion, "Suggestion" %>
      </div>
    </div>
    <div class="row">
      <%= f.button :submit, value: "Submit", class: "right", disable_with: "Please wait..." %>
    </div>


  </div>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Editing Suggestion</h1>

<%= render 'form', suggestion: @suggestion %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<div id="outter">
<div class="container" >
  <div class="w3-margin-top w3-border w3-border-black w3-round-large">
    <br><br>
    <%= render 'suggestions/form' %>
    <% if @suggestions.present? %>
      <% @suggestions.each do |suggestion| %>
          <div class="section w3-margin w3-padding w3-round-xlarge orange lighten-4">
            <%= link_to suggestion, class: "w3-hover-none flow-text" do %>
              <p class="flow-text">
                <i class="material-icons red-text ">
                  view_list
                </i>
                <span class="black-text w3-hover-none large">
               <%= suggestion.title %>
              </span>
                <span class="right w3-hover-none badge">
                <i class="">25</i> <i class="material-icons">comment</i>
              </span>
              </p>
            <% end %>
          </div>
      <% end %>
    <% else %>
      <h5 class="center w3-margin red darken-4 white-text">No Suggestions found!</h5>
    <% end %>
  </div>
</div>
</div>
<div class="clearfix"></div>
<br><br><br>

app/views/suggestions/new.js.erb
//(".me").html("<%#= escape_javascript(render(:partial =>"suggestions/form")) %>");
console.log("new.js file");
let body = document.getElementById('form');
body.innerHTML = "<%= j render 'form' %>"+body.innerHTML;

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @suggestion.title %>
</p>

<p>
  <strong>Suggestion:</strong>
  <%= @suggestion.suggestion %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @suggestion.active_status %>
</p>

<p>
  <strong>Del status:</strong>
  <%= @suggestion.del_status %>
</p>

<%= link_to 'Edit', edit_suggestion_path(@suggestion) %> |
<%= link_to 'Back', suggestions_path %>